# Generated by Django 3.0.4 on 2020-04-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
