# Generated by Django 3.0.4 on 2020-04-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answergiven',
            name='student_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
