# Generated by Django 3.0.4 on 2020-04-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_answer_is_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='problem_finished',
        ),
        migrations.AddField(
            model_name='problem',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
