# Generated by Django 3.0.4 on 2020-04-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='correct_answers_percentage',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
